### ISSUE TITLE
Grid Point Alignment Issue

### ISSUE THREAD

**Issue by Zhengxinyang** [wang-ps/mesh2sdf#1]
https://github.com/wang-ps/mesh2sdf/blob/776cbfc09f2a7f7fe938b0dc8daea222634c617e/csrc/pybind.cpp#L27

Should be

`Vec3f bbmin(-1.0f + 1.0f/float(size), -1.0f + 1.0f/float(size), -1.0f + 1.0f/float(size));`

**Comment by wang-ps** [comment]
Thanks.

Close this issue because (1) it is inconsistent with the behavior we expect in the experiments of our paper dual octree graph networks; (2) the marching cube algorithm takes volumetric field values defined on grid corners as input.
