### ISSUE TITLE
ModuleNotFoundError: No module named 'mesh2sdf.core'

### ISSUE THREAD

**Issue by ZZy129326999** [wang-ps/mesh2sdf#3]
```
import mesh2sdf.core
ModuleNotFoundError: No module named 'mesh2sdf.core'
```
I counter this problem, do you please help me? Thank you very much!!!

**Comment by wang-ps** [comment]
Please follow instructions to install `mesh2sdf`.  The error indicates that the installation process failed.

**https://github.com/wang-ps/mesh2sdf#installation**

**Comment by ZZy129326999** [comment]
Thank you! I also want to consult details about installation.
![image](https://github.com/wang-ps/mesh2sdf/assets/72543018/7ddbdda1-fe00-4873-b4af-34d9086edd3a)
I do not have counter some problem. I am very confused to it.

**Comment by ZZy129326999** [comment]
![Uploading image.png…]()

**Comment by ZZy129326999** [comment]
![image](https://github.com/wang-ps/mesh2sdf/assets/72543018/e6fb6127-438b-4d96-aff1-37a4c46c1a34)

**Comment by ZZy129326999** [comment]
???I use python3 can normally run it!!!!! python path is the primary problem. Thank you!
