### ISSUE TITLE
A question about the fast sweeping part

### ISSUE THREAD

**Issue by xmeng525** [wang-ps/mesh2sdf#4]
Hi Prof. Wang,
Thank you for the great implementation! I have a question about the [fast sweeping part](https://github.com/wang-ps/mesh2sdf/blob/bc6e2aabec685ed371dc3de0002b6ff6aa7b1959/csrc/makelevelset3.cpp#L163C4-L163C45).
According to Section 2.2 in [A fast sweeping method for eikonal equations](https://scholar.google.com/citations?view_op=view_citation&hl=zh-CN&user=zwBJ5LAAAAAJ&citation_for_view=zwBJ5LAAAAAJ:d1gkVwhDpl0C), for a 3D grid, we should get the correct SDF result by sweeping 8 times from the 8 different directions. 
However, in Line 163, the number of passes is two, which means that there are 16 sweeps in total.

I tried to change the number of pass to 1 (i.e. sweeping 8 times). And it did give the WRONG SDF result.
Would you please explain why we need two passes?
Thank you.

Best regards,
Xiaoxu

**Comment by wang-ps** [comment]
Please consult the author of the SDF code ( [Christopher Batty ](https://github.com/christopherbatty/SDFGen)) for more information.
