### ISSUE TITLE
ModuleNotFoundError: No module named 'mesh2sdf.core'; 'mesh2sdf' is not a package

### ISSUE THREAD

**Issue by XiangL-Xr** [wang-ps/mesh2sdf#6]
I get an error after installing the mesh2sdf library using the command "pip install mesh2sdf",  The error is, ”ModuleNotFoundError: No module named 'mesh2sdf.core'; 'mesh2sdf' is not a package“. Has anyone encountered the same error before? Please answer, Thanks.

**Comment by wang-ps** [comment]
Please follow instructions to install mesh2sdf. And C++ compilers are needed to build the code.

https://github.com/wang-ps/mesh2sdf#installation
