### ISSUE TITLE
How to get geometric bounding box of SDF?

### ISSUE THREAD

**Issue by kiegan-lenihan-xnilio** [wang-ps/mesh2sdf#8]
I have a mesh, and I assumed that the SDF calculated from said mesh is aligned with the bounding box of the mesh. So, if I want to get the SDF value at the `bbox_min` of the mesh, I would simply query `sdf[0, 0, 0]`. That seems incorrect however, it looks like the `mesh2sdf.compute()` function pads the geometry before aligning the grid. How do you tell this padding amount?

**Comment by wang-ps** [comment]
There is no padding.
You can refer to this function on how the SDF is computed:
 https://github.com/wang-ps/mesh2sdf/blob/master/csrc/pybind.cpp#L14
