### ISSUE TITLE
Why only keep the largest connected components for non-watertight meshes?

### ISSUE THREAD

**Issue by ForMyCat** [wang-ps/mesh2sdf#9]
Hi, thank you for open sourcing such a great work!

I am wondering why you only keep the largest connected component when computing the SDF. Sorry I am pretty new to SDF so this may be a dum question. Also, where can I find the source code for function "mesh2sdf.core.compute(vertices, faces, size)". I would like to learn how the SDF is actually computed.

**Comment by wang-ps** [comment]
> why you only keep the largest connected component when computing the SDF

There may be multiple components, and the largest one is the one we want to keep.  

> mesh2sdf.core.compute(vertices, faces, size)

https://github.com/wang-ps/mesh2sdf/blob/master/csrc/pybind.cpp
